import type { Post } from "./posts";

export const postsT18: Post[] = [
  {
    slug: "transporter-18-trzy-proby-pod-centra-danych",
    kicker: "Orbita",
    topic: "spacex",
    title: "Transporter-18 wyniósł trzy próby pod orbitalne centra danych",
    excerpt: "Falcon 9 wyniósł 1 października 130 ładunków, a wśród nich trzy satelity sprawdzające elementy centrów danych w kosmosie. Google testuje cztery układy TPU, Star Catcher chce przesłać energię między dwoma statkami, a Cowboy Space laserem klasy kilowatowej z orbity na Ziemię.",
    date: "3 października 2026",
    isoDate: "2026-10-03",
    img: "/img/transporter-18-falcon-9-start-vandenberg.jpg",
    credit: "Falcon 9 z misją Transporter-18 po starcie z bazy Vandenberg Space Force Base w Kalifornii, 1 października 2026 r. Fot. SpaceX, materiał prasowy ze strony misji",
    body: [
      {
        type: "p",
        text: "Wśród 130 ładunków, które Falcon 9 wyniósł 1 października z Kalifornii, znalazły się trzy satelity sprawdzające elementy przyszłych centrów danych w kosmosie. Google wysłał na orbitę cztery swoje układy TPU, Star Catcher chce przesłać energię między dwoma swobodnie lecącymi statkami, a Cowboy Space zamierza laserem klasy kilowatowej przesłać energię z orbity na Ziemię. Wszystkie trzy statki działają, ale żadna z prób przesyłu energii jeszcze się nie odbyła, a Google dopiero zaczyna zbierać dane.",
      },
      { type: "x", id: "2106095621765754963", handle: "outerspacetoday" },
      {
        type: "p",
        text: "Falcon 9 wystartował w czwartek 1 października o 11:32 czasu pacyficznego (20:32 w Polsce) ze stanowiska SLC-4E w bazie Vandenberg Space Force Base, jak podaje [strona misji Transporter-18](https://www.spacex.com/launches/transporter18). Był to lot zbiorczy dla małych satelitów. Według SpaceX na pokładzie było 130 ładunków: cubesaty, mikrosatelity, ładunki doczepione, dwa statki z kapsułami powrotnymi i cztery holowniki orbitalne, które później wypuszczą 41 z tych ładunków. Pierwszy stopień leciał po raz 25. i wylądował na lądowisku LZ-4. W harmonogramie wypuszczania ładunków SpaceX wymienia wszystkie trzy statki, o których mowa: Project Suncatcher M1, zgłoszony przez Planet Labs, oddzielił się w 62. minucie lotu, Reason-1 firmy Cowboy Space Corporation w 64. minucie, a Star Catcher Protostar w 65. minucie. [SpaceX potwierdził](https://x.com/SpaceX/status/2105762457255903623) wyniesienie wszystkich 130 ładunków.",
      },
      {
        type: "p",
        text: "Google [podał na X](https://x.com/Google/status/2105803583648100611), że prototypowy satelita zbudowany razem z firmą Planet niesie cztery układy TPU, czyli procesory, które Google projektuje do obliczeń sztucznej inteligencji. Start jest pierwszym krokiem Project Suncatcher, długofalowego projektu badawczego, który ma sprawdzić, czy w kosmosie da się kiedyś umieścić skalowalną infrastrukturę uczenia maszynowego. Travis Beals, starszy dyrektor w Google, napisał na [blogu firmy](https://blog.google/innovation-and-ai/models-and-research/google-research/project-suncatcher-prototype/), że zespół nawiązał kontakt z satelitą i że działa on zgodnie z oczekiwaniami. Przez najbliższe tygodnie Google chce zbierać dane o tym, jak TPU znoszą obciążenia lotu, promieniowanie i skrajne temperatury. Razem z tym wpisem firma udostępniła recenzowany artykuł naukowy o projekcie, opublikowany w czasopiśmie Joule.",
      },
      {
        type: "p",
        text: "Szczegóły testów Google opisał w [tekście z 24 września](https://blog.google/innovation-and-ai/models-and-research/google-research/google-project-suncatcher-facts/). Podczas startu statek doznaje przeciążeń do 10 g, a pojedyncze podzespoły, takie jak układy TPU, nawet 50–100 g. Na Ziemi zespół wytrząsał satelitę we wszystkich trzech osiach, a układy TPU Trillium sprawdzał w wiązce protonów w Crocker Nuclear Laboratory na Uniwersytecie Kalifornijskim w Davis, gdy wykonywały obliczenia AI. Według Google przetrwały dawkę promieniowania jonizującego większą niż ta, którą otrzymałyby w ciągu pięcioletniej misji. Drugim problemem jest chłodzenie, bo w próżni ciepło można oddawać tylko przez radiatory. Google połączył rurki cieplne z radiatorami i testował to rozwiązanie w komorze próżniowej, a na orbicie chce sprawdzić, jak działa w prawdziwych warunkach. Firma przypomina, że na niskiej orbicie satelita ma niemal stały dostęp do Słońca i może wytworzyć do ośmiu razy więcej energii słonecznej niż na Ziemi. Docelowe satelity mają nieść po kilkadziesiąt układów TPU i latać w zwartych gromadach połączonych laserami. Takie łącza Google chce sprawdzić w 2027 r. na dwóch kolejnych satelitach.",
      },
      {
        type: "p",
        text: "Star Catcher Industries z Jacksonville na Florydzie nie testuje komputerów, tylko zasilanie. W [komunikacie z 28 września](https://www.star-catcher.com/news/protostar-announcement) firma napisała, że Protostar po uruchomieniu wypuści i namierzy cubesata, a potem skieruje na jego zwykłe, seryjne panele słoneczne wiązkę światła o mierzalnej mocy. Jeśli próba się uda, będzie to według Star Catcher pierwszy na świecie optyczny przesył energii między dwoma swobodnie lecącymi statkami. Partnerem misji jest Defense Innovation Unit, jednostka Pentagonu do współpracy z firmami technologicznymi, która [podała](https://x.com/DIU_x/status/2105730829641015347), że na orbitę trafiły nadajnik Protostar i odbiornik DemoCatcher-1. Po starcie Star Catcher [zapowiedział](https://x.com/StarCatcherInd/status/2105746431143280806), że próba odbędzie się w ciągu najbliższych miesięcy, a 2 października [poinformował](https://x.com/StarCatcherInd/status/2106100881208885456), że Protostar wytwarza więcej energii, niż zużywa, i łączy się z zespołem na Ziemi. „Każde ważne zastosowanie napędzające gospodarkę kosmiczną, od rozpoznania w czasie rzeczywistym na potrzeby bezpieczeństwa narodowego po orbitalne obliczenia AI i obserwację Ziemi, jest ograniczone przez dostępną moc” – powiedział Andrew Rush, współzałożyciel i prezes Star Catcher.",
      },
      {
        type: "p",
        text: "Firma założona w 2024 r. ustanowiła na Ziemi, w Centrum Kosmicznym im. Kennedy'ego, rekord świata w optycznym przesyle energii, a pod koniec 2025 r. sprawdziła na orbicie w misji Sextant Alpha swoje oprogramowanie do namierzania satelitów. Star Catcher ogłosił 10 umów na sprzedaż energii, m.in. ze Starcloud, Loft Orbital, Astro Digital i Aethero, i ma ponad 40 listów intencyjnych. Zebrał 88 mln dolarów (ok. 342 mln zł) od funduszy venture capital, a od Sił Kosmicznych USA dostał 60 mln dolarów w programie STRATFI. Na [swojej stronie](https://www.star-catcher.com) firma wyjaśnia, że jej sieć ma przesyłać skoncentrowaną energię słoneczną na panele, które satelity już mają, bez przeróbek sprzętu.",
      },
      {
        type: "p",
        text: "Cowboy Space Corporation, wcześniej działająca pod nazwą Aetherflux, chce przesyłać energię w przeciwną stronę, z orbity na Ziemię. Firmę założył Baiju Bhatt, współzałożyciel Robinhooda. 28 września Cowboy Space [napisał](https://x.com/CowboySpaceCorp/status/2104658525750513991), że zadaniem Reason-1 jest sprawdzenie przesyłu energii laserem dużej mocy z niskiej orbity do odbiornika na Ziemi. „Jeśli chcesz budować centra danych w kosmosie, musisz opanować układy optyczne między orbitą a Ziemią” – dodała firma. Że chodzi o laser podczerwony, Cowboy Space podał w [maju](https://x.com/CowboySpaceCorp/status/2057967254072152527): pierwszy satelita ma przesłać energię z kosmosu na Ziemię w podczerwieni i sprawdzić zbudowany przez firmę laser o mocy ponad 1 kW. Już w 2024 r. Bhatt [tłumaczył](https://x.com/BaijuBhatt/status/1844063967020458425), że jego firma zamiast mikrofal użyje laserów podczerwonych, bo pozwalają uzyskać większą moc przy mniejszych stacjach odbiorczych na Ziemi.",
      },
      {
        type: "p",
        text: "W [komunikacie z dnia startu](https://finance.yahoo.com/technology/articles/cowboy-space-launches-reason-1-194400031.html) Cowboy Space napisał, że Reason-1 zbierze energię słoneczną w kosmosie i prześle ją do odbiornika na Ziemi laserem klasy kilowatowej, pierwszym komercyjnym laserem tej klasy w kosmosie. Firma sama zaprojektowała lasery, teleskop o dużej aperturze i system kierowania wiązką. Doświadczenia z tych układów mają posłużyć do budowy sieci łączności optycznej dla jej orbitalnych centrów danych, a dane o zasilaniu i chłodzeniu mają pomóc w obsłudze serwerowych procesorów graficznych w kosmosie. „Reason-1 to pierwszy krok w tę przyszłość i pierwszy etap zasilania ludzkości z orbity” – powiedział Bhatt. Ładunek leci na platformie satelitarnej firmy Apex. Apex [podał](https://x.com/Apex_Spacecraft/status/2105827483258167460), że satelita ustawił panele do Słońca, wytwarza więcej energii, niż zużywa, ma pełną łączność w obu kierunkach i odezwał się w ciągu 10 minut od oddzielenia od rakiety. 2 października Cowboy Space [zapowiedział](https://x.com/CowboySpaceCorp/status/2106088811373670884), że w ciągu najbliższych tygodni zespół będzie pracował nad głównym celem misji, czyli przesłaniem energii z orbity na Ziemię.",
      },
      {
        type: "p",
        text: "Reason-1 jest dla Cowboy Space dopiero początkiem. Reason-2 ma polecieć w 2027 r. i przesyłać dane optycznie z kosmosu na Ziemię z prędkością bliską rekordowej. W [majowym wpisie](https://x.com/CowboySpaceCorp/status/2057967254072152527) firma zapowiedziała też na początek 2027 r. lot z pierwszymi procesorami graficznymi, które mają pracować w kosmosie z przerwami i zebrać dane o promieniowaniu. Cowboy Space buduje też własną rakietę, której górny stopień ma zostać na orbicie jako centrum danych o mocy 1 MW, i współpracuje z NVIDIA przy umieszczeniu na niskiej orbicie modułów NVIDIA Space-1 Vera Rubin. W maju firma podała, że w rundzie finansowania pozyskała 275 mln dolarów (ok. 1,07 mld zł) przy wycenie 2 mld dolarów.",
      },
      {
        type: "p",
        text: "SpaceX ma własny plan orbitalnych centrów danych pod nazwą Starmind. Na [stronie projektu](https://www.spacex.com/spacexai/starmind) firma opisuje satelity AI1 na orbicie synchronicznej ze Słońcem, które same wykonują obliczenia AI, a wyniki przesyłają laserami do Ziemi przez sieć Starlink. Rozłożony satelita ma mieć 30 m wysokości i 75 m rozpiętości, a jego ładunek obliczeniowy ma pobierać do 250 kW mocy szczytowej i średnio 175 kW. Ciepło mają odprowadzać w próżnię rozkładane radiatory cieczowe, dzięki czemu według SpaceX energia potrzebna na chłodzenie spada o rząd wielkości w porównaniu z centrami danych na Ziemi. Fabryka Gigasat w Bastrop w Teksasie ma produkować tysiące takich satelitów, najwcześniej od końca 2027 r., a do ich wynoszenia potrzebny jest Starship. 4 sierpnia SpaceX [ogłosił](https://x.com/SpaceX/status/2084723854534951218), że ładunek obliczeniowy satelitów Starmind projektuje razem z NVIDIA i że każdy z nich będzie miał procesory graficzne Rubin i procesory Vera. Jak SpaceX łączy te satelity ze Starlinkiem, opisaliśmy w tekście [Superkomputer na Starlinku to jeszcze nie Starmind](https://muskonomia.pl/blog/superkomputer-starlink-to-jeszcze-nie-starmind).",
      },
      {
        type: "p",
        text: "SpaceX złożył 30 stycznia 2026 r. w amerykańskiej Federalnej Komisji Łączności (FCC) wniosek o zgodę na system do miliona satelitów pod nazwą SpaceX Orbital Data Center. Według [komunikatu FCC z 4 lutego](https://docs.fcc.gov/public/attachments/DA-26-113A1.pdf), w którym komisja przyjęła wniosek do rozpatrzenia, satelity mają krążyć na wysokości od 500 do 2000 km i łączyć się laserami ze sobą oraz z satelitami Starlink. W [prospekcie emisyjnym z 11 czerwca](https://www.sec.gov/Archives/edgar/data/1181412/000162828026042639/spaceexplorationtechnologi.htm) SpaceX podał, że 2 lutego 2026 r. przejął xAI, która od tego dnia jest jego spółką zależną w całości, i że pierwsze satelity do obliczeń AI chce zacząć wynosić najwcześniej w 2028 r. Elon Musk [napisał](https://x.com/elonmusk/status/2088306926442430578) 14 sierpnia, że obliczenia na orbicie staną się jedynym sposobem skalowania AI prawdopodobnie w 2029 r., bo na Ziemi brakuje mocy i trudno o pozwolenia. O Project Suncatcher Musk mówił też w [rozmowie w Białym Domu](https://muskonomia.pl/blog/musk-huang-bialy-dom), a pozostałe starty SpaceX z tego tygodnia opisaliśmy w tekście o tym, jak [SpaceX w jednym tygodniu wystrzelił wszystkie trzy swoje rakiety](https://muskonomia.pl/blog/spacex-tydzien-wszystkie-trzy-rakiety).",
      },
    ],
  },
];
