import type { Post } from "./posts";

export const postsB: Post[] = [
{
    slug: "tesla-model-y-dla-rodziny",
    kicker: "Tesla",
    topic: "tesla",
    title: "Model Y: auto, ktore ogarnia rodzine",
    excerpt: "Miejsce, cisza, foteliki, bagaznik i siec Superchargerow. Krotko: dlaczego Y jest codziennym autem Tesli.",
    date: "21 sierpnia 2026",
    isoDate: "2026-08-21",
    img: "/img/modely-hero.jpg",
    body: [
      { type: "p", text: "Cybertruck i Semi robia zdjecia. Model Y wozi dzieci do szkoly. To najczesciej spotykana Tesla na swiecie — foteliki, wozek, weekend i zimowy wyjazd." },
      { type: "img", src: "/img/modely-hero.jpg", alt: "Tesla Model Y przy Superchargerze", caption: "Juniper: nizszy, cichszy, latwiejszy w miescie. Ladowanie w sieci, ktora juz znasz." },
      { type: "h2", text: "Miejsce, ktore naprawde jest" },
      { type: "p", text: "Piecioro doroslych bez kombinowania. Opcjonalny trzeci rzad — ciasny, ale ratuje wyjazd z dziadkami albo dwiema parami fotelikow. Plaska podloga (brak tunelu) znaczy, ze srodkowe dziecko nie siedzi na wale." },
      { type: "img", src: "/img/modely-row.jpg", alt: "Trzeci rzad Model Y", caption: "Trzeci rzad jest niski — dla dzieci i krotkich tras, nie na maraton. Skladany w sekunde." },
      { type: "h2", text: "Bagaznik, frunk i wozek" },
      { type: "p", text: "Klapa unosi sie wysoko, prog jest niski, podloga bagaznika plaska. Wozek wchodzi bez demontazu kol. Frunk bierze kable, kamizelki i brudne rzeczy z dala od kanap." },
      { type: "img", src: "/img/modely-trunk.jpg", alt: "Bagaznik Tesla Model Y", caption: "Jeden duzy kufer plus frunk. Na tydzien w gorach starcza bez boksu na dachu." },
      { type: "h2", text: "Bezpieczenstwo i spokoj" },
      { type: "p", text: "Niska bateria w podlodze, sztywne nadwozie, topowe oceny crash-testow. Autopilot na autostradzie zdejmuje zmeczenie z rodzicow, nie z odpowiedzialnosci." },
      { type: "img", src: "/img/interior.jpg", alt: "Szklany dach Model Y", caption: "Szklany dach i duzo swiatla. W upale klimatyzacja wstepnie chlodzi auto z telefonu." },
      { type: "h2", text: "Codziennosc, nie show" },
      { type: "ul", items: ["Cisza — rozmowa z tylnej kanapy bez krzyku", "Zero oleju, przegledow skrzyni i DPF-u", "Domowy wallbox: rano zawsze pelny bak", "Superchargery na trasie wakacji", "Ogrzewanie foteli i kierownicy zima od razu"] },
      { type: "p", text: "Model Y nie obiecuje Marsa. Obiecuje, ze wtorek o 7:40 i powrot z basenu w piatek zmieszcza sie w jednym aucie." },
    ],
  },
{
    slug: "terafab-ruszyly-pierwsze-prace-budowlane",
    kicker: "Tesla / xAI",
    topic: "tesla",
    title: "Terafab: ruszyl pierwsze prace budowlane",
    excerpt: "SpaceX i Tesla ruszyl z przygotowaniem terenu pod fabryke chipow. Prototyp w Austin, pelna skala w Grimes County.",
    date: "17 sierpnia 2026",
    isoDate: "2026-08-17",
    img: "/img/terafab-render-night.jpg",
    body: [
      { type: "p", text: "Terafab to wspolny zaklad chipow Tesli i SpaceX. Projektowanie, logika, pamiec, advanced packaging i testy pod jednym dachem. Cel pierwszej pelnej skali: ponad 1 terawat mocy obliczeniowej AI rocznie." },
      { type: "p", text: "Ogloszenie: 21 marca 2026. Potwierdzenie lokalizacji i parametrow fazy 1: 6 sierpnia 2026. Dwa place: prototyp w Austin i pelny kompleks przy zbiorniku Gibbons Creek w hrabstwie Grimes." },
      { type: "h2", text: "Wizja — jak ma wygladac" },
      { type: "img", src: "/img/terafab-render-night.jpg", alt: "Wizualizacja nocna kompleksu Terafab", caption: "Render: skrzydla hali nad terenem Grimes, zbiornik w tle." },
      { type: "p", text: "Docelowo ponad 100 milionow stop kwadratowych. SpaceX mowi o wielofazowej inwestycji nawet do 119 mld USD. Faza 1: 16,8 mld USD, minimum 3 tys. miejsc pracy." },
      { type: "img", src: "/img/cover-terafab.jpg", alt: "Porownanie skali Terafab z boiskiem NFL", caption: "Oficjalna grafika skali: boisko NFL ginie w planie hali." },
      { type: "h2", text: "Prototyp w Austin — juz stoi i kopie" },
      { type: "img", src: "/img/terafab-atf.jpg", alt: "Advanced Technology Fab Giga Texas", caption: "North Campus Giga Texas: budynek Tesla / xAI / SpaceX." },
      { type: "p", text: "Advanced Technology Fab ruszyla w kwietniu 2026 na terenie Giga Texas. Koszt rzedu 3 mld USD, kilka tysiecy waferow miesiecznie. Intel zadeklarowal wsparcie procesu 14A." },
      { type: "img", src: "/img/terafab-terrain.jpg", alt: "Prace ziemne przy Giga Texas", caption: "Aktualny teren: pale, zurawie, place skladowe obok hali Giga Texas." },
      { type: "h2", text: "Grimes County" },
      { type: "p", text: "3 czerwca 2026 hrabstwo zatwierdzilo strefe reinwestycji i abatament podatkowy. Woda ma isc ze zbiornika Gibbons Creek. Do polowy sierpnia 2026: wycinka i przygotowanie terenu w Grimes, pale i place w Austin." },
      { type: "p", text: "Terafab ma zasilic ten sam stack co Colossus i Starship: krzem, energia, wynoszenie." },
    ],
  },
{
    slug: "grok-46-wchodzi-do-scislej-czolowki-medycznych-benchmarkow",
    kicker: "xAI",
    topic: "xai",
    title: "Grok 4.6 w scislej czolowce medycznych benchmarkow",
    excerpt: "Wersja high zdobyla 50 pkt w Artificial Analysis Healthcare and Medical Index — punkt za liderem.",
    date: "17 sierpnia 2026",
    isoDate: "2026-08-17",
    img: "/img/grok-chart.jpg",
    contain: true,
    body: [
      { type: "p", text: "Grok 4.6 znalazl sie w pierwszej trojce rankingu Artificial Analysis Healthcare and Medical Index. Wersja high: 50 punktow, zaledwie punkt za liderem (51)." },
      { type: "p", text: "Indeks ocenia wiedze medyczna, rozumowanie kliniczne, dokumentacje pacjenta, ograniczanie halucynacji i agentyczne workflow." },
      { type: "img", src: "/img/grok-chart.jpg", alt: "Artificial Analysis Healthcare Index", caption: "Grok 4.6 high: 50 pkt, punkt za liderem.", contain: true },
      { type: "p", text: "Zrodlo: post @XFreeze na X." },
    ],
  },
{
    slug: "tesla-gotowa-na-wystartowanie-uslugi-cybercab",
    kicker: "Tesla",
    topic: "tesla",
    title: "Tesla gotowa na start uslugi Cybercab",
    excerpt: "Roll-out w Austin: najpierw pracownicy, potem oficjalne Robotaxi. Dwuosobowy pojazd bez kierownicy i pedallow.",
    date: "17 sierpnia 2026",
    isoDate: "2026-08-17",
    img: "/img/cover-cybercab.jpg",
    body: [
      { type: "p", text: "Tesla ma wkrotce rozpoczac publiczne testy Cybercaba — auta dedykowanego robotaxi. Pierwszy etap: sierpien 2026, Austin w Teksasie." },
      { type: "p", text: "17 sierpnia media podaly, ze Tesla poinformowala pracownikow o roll-oucie. Najpierw przejazdy zalogi po drogach publicznych, kilka dni pozniej wlaczenie do oficjalnej uslugi Robotaxi w Austin." },
      { type: "p", text: "Cybercab to dwuosobowy pojazd autonomiczny bez kierownicy i pedallow. Produkcyjne egzemplarze jezdzily po drogach od czerwca 2026." },
      { type: "img", src: "/img/robotaxi.jpg", alt: "Tesla Robotaxi na ulicy", caption: "Najpierw Model Y z kierowca-bezpiecznikiem, potem Cybercab." },
    ],
  },
{
    slug: "tesla-semi-pelna-specyfikacja-elektrycznego-giganta-produkcja-masowa-rusza-w-2026",
    kicker: "Tesla",
    topic: "tesla",
    title: "Tesla Semi: pelna specyfikacja, produkcja masowa w 2026",
    excerpt: "Standard Range i Long Range, trzy silniki, 800 kW, ladowanie MCS do 1,2 MW. Fabryka w Sparks, Nevada.",
    date: "17 lutego 2026",
    isoDate: "2026-02-17",
    img: "/img/cover-cybercab.jpg",
    body: [
      { type: "p", text: "W lutym 2026 Tesla ujawnila parametry Semi tuz przed startem seryjnej produkcji w Sparks w Nevadzie. Dwie wersje: Standard Range i Long Range." },
      { type: "h2", text: "Dwie wersje" },
      { type: "p", text: "Standard Range: ok. 325 mil (523 km) przy 82 000 funtow GCW, masa wlasna ponizej 20 000 funtow, 1,7 kWh/mile, bateria ok. 550 kWh, cena ok. 250-260 tys. USD." },
      { type: "p", text: "Long Range: ok. 500 mil (805 km), 23 000 funtow wlasnej, bateria ok. 850-875 kWh, 290 tys. USD." },
      { type: "h2", text: "Napęd" },
      { type: "img", src: "/img/inline-semi.jpg", alt: "Tesla Semi w ruchu", caption: "Trzy silniki, 800 kW. Na 5% wzniesieniu Semi trzyma 65 mph." },
      { type: "p", text: "Trzy niezalezne silniki, 800 kW (ok. 1088 KM). 0-60 mph w 20 s z pelnym ladunkiem." },
      { type: "h2", text: "Ladowanie" },
      { type: "p", text: "Standard MCS 3.2. Long Range do 1,2 MW. 60% w 30 minut — ok. 300 mil dodatkowego zasiegu." },
      { type: "p", text: "Produkcja masowa w 2026, potencjal nawet 50 000 sztuk rocznie." },
    ],
  },
{
    slug: "rivian-spalil-wiecej-gotowki-niz-tesla-zarobila-jeden-wykres-mowi-wszystko",
    kicker: "Inne",
    topic: "inne",
    title: "Rivian spalil wiecej gotowki, niz Tesla zarobila",
    excerpt: "Kumulacyjny FCF: Tesla +21,7 mld USD, Rivian –24,4 mld. Jeden wykres pokazuje przepasc pure-EV.",
    date: "14 lutego 2026",
    isoDate: "2026-02-14",
    img: "/img/inline-rivian.jpg",
    body: [
      { type: "p", text: "13 lutego 2026 na X kraży wykres AJ Financial Research (@alojoh): kumulacyjny free cash flow marek EV od startu do poczatku 2026." },
      { type: "ul", items: ["Tesla: +21,7 mld USD", "Rivian: –24,4 mld USD"] },
      { type: "p", text: "Rivian spalil o ponad 2,7 mld wiecej, niz Tesla wygenerowala przez cala historie od 2003. Tesla rysuje kij hokejowy: lata strat, potem eksplozja." },
      { type: "img", src: "/img/inline-rivian.jpg", alt: "Rivian R1T", caption: "Rivian R1T/R1S: duzy produkt, wciaz gleboki minus w kumulacyjnym FCF." },
      { type: "p", text: "FCF w motoryzacji to test przetrwania. Wykres to surowe dane ze sprawozdan: Tesla jest wyjatkiem, nie regula." },
    ],
  },
{
    slug: "starlink-przekracza-10-milionow-aktywnych-klientow",
    kicker: "SpaceX",
    topic: "spacex",
    title: "Starlink przekracza 10 milionow aktywnych klientow",
    excerpt: "Z 9 milionow na przelomie roku do 10 milionow w poltora miesiaca. Okolo 20 tysiecy nowych abonentow dziennie.",
    date: "14 lutego 2026",
    isoDate: "2026-02-14",
    img: "/img/cover-starlink.jpg",
    body: [
      { type: "p", text: "13 lutego 2026 ogłoszono kamien milowy: ponad 10 milionow aktywnych subskrybentow Starlinka. Tempo: z 9 mln na przelomie roku, srednio 19,6-20 tys. klientow dziennie." },
      { type: "h2", text: "Jak szybko to poszlo" },
      { type: "ul", items: ["Grudzien 2024 — ~4,6 mln", "Sierpien 2025 — 7 mln", "Listopad 2025 — 8 mln", "Grudzien 2025 — 9 mln", "Luty 2026 — >10 mln"] },
      { type: "img", src: "/img/inline-starlink-dish.jpg", alt: "Antena Starlink na dachu", caption: "10 milionow aktywnych terminali — internet tam, gdzie nie ma innego." },
      { type: "p", text: "Zasieg w ponad 155 krajach. Przy ~20 tys. dziennie 15 milionow jeszcze w tym roku jest w zasiegu. Z zera w 2020 do 10 milionow w 2026 — to juz nie eksperyment." },
    ],
  },
{
    slug: "spacex-stawia-ksiezyc-przed-marsem-elon-musk-oglasza-pivot-na-self-growing-city",
    kicker: "SpaceX",
    topic: "spacex",
    title: "SpaceX stawia Ksiezyc przed Marsem",
    excerpt: "Musk: self-growing city na Ksiezycu w mniej niz 10 lat. Mars zostaje celem, ale schodzi na drugi plan.",
    date: "11 lutego 2026",
    isoDate: "2026-02-11",
    img: "/img/cover-moon.jpg",
    body: [
      { type: "p", text: "W postach z 8 i 9 lutego 2026 Musk oglosil, ze SpaceX przesuwa fokus na samorozwijajace sie miasto na Ksiezycu, bo da sie to zrobic w mniej niz 10 lat, podczas gdy Mars zajmie ponad 20." },
      { type: "h2", text: "Dlaczego Ksiezyc i dlaczego teraz" },
      { type: "img", src: "/img/cover-falcon.jpg", alt: "Falcon 9 — Floryda i Kalifornia", caption: "Czeste starty. Na Ksiezyc okno co ~10 dni, na Marsa co 26 miesiecy." },
      { type: "p", text: "Okno na Marsa co 26 miesiecy, lot ok. 6 miesiecy. Na Ksiezyc start co ok. 10 dni, lot 2 dni. Iteracja systemow zycia, logistyki i energii moze byc ekstremalnie szybka." },
      { type: "h2", text: "Mars nie jest porzucony" },
      { type: "p", text: "Prace marsjanskie maja ruszyc za 5-6 lat, rownolegle. Najpierw nauczyc sie zyc poza Ziemia na najblizszym terenie." },
    ],
  },
{
    slug: "xai-kolos-na-drewnianych-nogach",
    kicker: "xAI",
    topic: "xai",
    title: "xAI: kolos na drewnianych nogach?",
    excerpt: "Fuzja ze SpaceX, Series E na 20 mld, Colossus, Imagine 1.0 — i nierozwiazany problem tresci. Rollercoaster 2026.",
    date: "11 lutego 2026",
    isoDate: "2026-02-11",
    img: "/img/cover-terafab.jpg",
    body: [
      { type: "p", text: "Poczatek 2026 w xAI: fuzja, miliardowe rundy, wideo w czolowce benchmarkow i kontrowersje wokol Groka, ktore nie gasna." },
      { type: "p", text: "2 lutego ogloszono fuzje xAI ze SpaceX. Laczna wycena ok. 1,25 bln dolarow (SpaceX ~1 bln, xAI ~250 mld). One Team." },
      { type: "p", text: "Tuz przed fuzja Series E: 20 mld USD, glownie Colossus (ponad 200 tys. GPU, cel miliona) i produkty. Grok Imagine API i Imagine 1.0." },
      { type: "img", src: "/img/inline-colossus.jpg", alt: "Colossus — klaster treningowy xAI", caption: "Ponad 200 tys. GPU. Cel: milion. Stad ida Grok i Imagine." },
      { type: "ul", items: ["Wycena xAI przed fuzja: ~230-250 mld USD", "Colossus: 200 tys.+ GPU", "Grok 5 w treningu", "Musk: AGI moze w 2026, optymistycznie"] },
      { type: "p", text: "xAI weszlo w 2026 nie jako challenger, tylko jako gracz z zasobami, ktorych inni nie maja." },
    ],
  },
];
