import type { Post } from "./posts";

export const postsA: Post[] = [
{
    slug: "jesli-anthropic-wart-2-biliony-ile-wart-spacex",
    kicker: "SpaceX",
    topic: "spacex",
    title: "Jesli Anthropic jest wart 2 biliony dolarow, to ile powinien byc wart SpaceX?",
    excerpt: "Grok, Colossus, X, Starlink, rakiety i satelity. Rynek wycenia sama firme AI na 2 bln — SpaceX ma caly lancuch, w tym klienta o nazwie Anthropic.",
    date: "21 sierpnia 2026",
    isoDate: "2026-08-21",
    img: "/img/falcon-sunset.jpg",
    body: [
      { type: "p", text: "Na X pojawil sie ciekawy argument dotyczacy wyceny SpaceX. Autor zwraca uwage na cos, co coraz trudniej bagatelizowac: firme, ktora wiekszosc ludzi wciaz kojarzy glownie z rakietami, buduje dzis znacznie szerszy i bardziej zintegrowany stack." },
      { type: "img", src: "/img/falcon-sunset.jpg", alt: "Falcon 9 startujacy o zachodzie slonca", caption: "Rakiety to wciaz twarz SpaceX. Pod spodem jest juz caly stack AI." },
      { type: "h2", text: "Co SpaceX ma dzis" },
      { type: "ul", items: ["Groka, ktory regularnie poprawia wyniki w benchmarkach", "Colossus — jeden z najwiekszych superkomputerow AI na swiecie", "platforme X: dystrybucja modelu i staly dostep do aktualnych danych", "Starlink — globalna siec komunikacyjna", "rakiety wielokrotnego uzytku, ktorymi wynoszone sa satelity", "wlasne satelity", "plany umieszczania mocy obliczeniowej AI na orbicie"] },
      { type: "img", src: "/img/inline-colossus.jpg", alt: "Klaster GPU Colossus", caption: "Colossus. Wiekszosc laboratoriow AI kupuje compute. SpaceX go buduje — i sprzedaje." },
      { type: "p", text: "Wiekszosc firm AI musi kupowac lub wynajmowac ogromne ilosci compute. SpaceX buduje te moc samodzielnie. Do tego stopnia, ze Anthropic — jedna z najwyzej wycenianych spolek AI na swiecie — jest juz klientem SpaceXAI i korzysta z Colossusa." },
      { type: "p", text: "To wazna zmiana perspektywy. Firma, ktora rynek wciaz czesto traktuje przede wszystkim jako rakietowa, stala sie dostawca krytycznej infrastruktury dla czolowych graczy sektora sztucznej inteligencji." },
      { type: "img", src: "/img/grok-chart.jpg", alt: "Grok w rankingach modeli", caption: "Grok pnie sie w benchmarkach. Model siedzi w tym samym domu co rakiety i Starlink.", contain: true },
      { type: "h2", text: "Caly lancuch" },
      { type: "p", text: "W uproszczeniu SpaceX kontroluje dzis niemal caly lancuch: model + moc obliczeniowa + dane + dystrybucja + lacznosc + rakiety + satelity." },
      { type: "img", src: "/img/cover-starlink.jpg", alt: "Slady satelitow Starlink na niebie", caption: "Starlink: wlasne satelity, wlasna lacznosc, wlasne starty. Potem compute na orbicie." },
      { type: "p", text: "Docelowo chce miec tez znaczaca czesc compute znajdujacego sie nad Ziemia." },
      { type: "img", src: "/img/inline-starlink-dish.jpg", alt: "Antena Starlink", caption: "Dystrybucja nie jest aplikacja w store. Jest terminalem na dachu i rakieta, ktora ten terminal zasila." },
      { type: "h2", text: "Wycena" },
      { type: "p", text: "Autor wpisu argumentuje, ze jesli rynek uznaje za uzasadniona wycene rzedu 2 bilionow dolarow dla samodzielnej firmy AI (takiej jak Anthropic), to trudno zakladac, ze SpaceX — posiadajacy wyraznie szerszy i bardziej zintegrowany stack — zatrzyma sie w okolicach obecnych wycen." },
      { type: "p", text: "Czy to zbyt optymistyczne? Czesciowo tak. Ale sama logika jest warta uwagi. SpaceX nie jest juz tylko firma rakietowa. Systematycznie buduje infrastrukture, na ktorej coraz mocniej opiera sie rozwoj AI." },
    ],
  },
{
    slug: "elon-musk-starship-is-so-sci-fi",
    kicker: "SpaceX",
    topic: "spacex",
    title: "Elon Musk: Starship is so sci-fi",
    excerpt: "Musk wrzucil zdjecie odzyskanego Starshipa na oceanie. Uszkodzone plytki, wgniecenia, lodz ratunkowa.",
    date: "21 sierpnia 2026",
    isoDate: "2026-08-21",
    img: "/img/starship-scifi.jpg",
    body: [
      { type: "p", text: "Elon Musk opublikowal zdjecie odzyskanego Starshipa unoszacego sie na oceanie. Widac na nim slady intensywnego powrotu – uszkodzone i brakujace plytki oslony termicznej, wgniecenia oraz zespol ratunkowy na lodzi obok." },
      { type: "img", src: "/img/starship-scifi.jpg", alt: "Starship po powrocie", caption: "Kadr z wpisu Muska na X — pojazd po trudnym powrocie." },
      { type: "p", text: "Podpis jest krotki i celny: Starship is so sci-fi." },
      { type: "img", src: "/img/starship-tower-night.jpg", alt: "Starship — skala pojazdu", caption: "Ogromny, metaliczny, czesciowo okopcony. Wyglada jak wyjetty z science-fiction." },
      { type: "p", text: "Fotografia dobrze oddaje skale i charakter programu. Nawet po trudnym powrocie pojazd wyglada jak cos wyjetego prosto z science-fiction – ogromny, metaliczny, czesciowo okopcony, dryfujacy na wodzie." },
    ],
  },
{
    slug: "tesla-dostala-zielone-swiatlo-na-robotaxi-w-nevadzie-do-5000-pojazdow",
    kicker: "Tesla",
    topic: "tesla",
    title: "Tesla dostala zielone swiatlo na Robotaxi w Nevadzie",
    excerpt: "Nevada Transportation Authority zatwierdzila siec do 5000 robotaxi. Clark County, potem caly stan.",
    date: "21 sierpnia 2026",
    isoDate: "2026-08-21",
    img: "/img/cover-cybercab.jpg",
    body: [
      { type: "p", text: "Tesla oficjalnie otrzymala pelne pozwolenie na dzialalnosc jako Autonomous Vehicle Network Company w Nevadzie. Komisja Nevada Transportation Authority zatwierdzila wniosek 20 sierpnia 2026." },
      { type: "p", text: "Pozwolenie obejmuje cale hrabstwo Clark (w tym Las Vegas) i — wedlug komisji — umozliwia operacje w calym stanie, po wczesniejszym powiadomieniu o rozszerzeniu geofence." },
      { type: "img", src: "/img/inline-vegas.jpg", alt: "Las Vegas Strip noca", caption: "Hrabstwo Clark, w tym Las Vegas — pierwszy pelny rynek Robotaxi Tesli w Nevadzie." },
      { type: "h2", text: "Co zatwierdzono" },
      { type: "ul", items: ["Flota do 5000 robotaxi w ciagu 12 miesiecy", "Usluga platna, publiczna", "Start z mala liczba pojazdow, stopniowe skalowanie", "Pierwsze auta: Model Y, Cybercab pozniej"] },
      { type: "p", text: "To zastepuje wczesniejsze tymczasowe pozwolenie, ktore ograniczalo Tesle do 10 pojazdow." },
      { type: "p", text: "Self-certification Tesla zamknela w listopadzie 2025, wniosek zlozyla 3 czerwca 2026. Zostaly inspekcje, ubezpieczenie i taryfy — okolo 30 dni." },
      { type: "h2", text: "Kontekst" },
      { type: "img", src: "/img/robotaxi.jpg", alt: "Tesla Robotaxi Model Y", caption: "Na start: Model Y. Cybercab dolaczy pozniej." },
      { type: "p", text: "Tesla nie planuje od razu pelnych 5000. Realistyczny cel na rok to kilka tysiecy. W tym samym posiedzeniu Waymo i Uber dostaly po 1000 pojazdow. Las Vegas dochodzi do Austin, Dallas i Houston." },
    ],
  },
{
    slug: "nowy-megacharger-tesli-w-vernon-kalifornia",
    kicker: "Tesla",
    topic: "tesla",
    title: "Nowy Megacharger Tesli w Vernon, Kalifornia",
    excerpt: "Druga publiczna stacja 1,2 MW dla Semi. Szesc stanowisk w sercu logistyki portow LA i Long Beach.",
    date: "21 sierpnia 2026",
    isoDate: "2026-08-21",
    img: "/img/cover-megacharger.jpg",
    body: [
      { type: "p", text: "Tesla otworzyla Megacharger w Vernon w Kalifornii (3130 Bandini Blvd). To druga lokalizacja w pelni publiczna dla klientow Tesla Semi." },
      { type: "p", text: "Stacja: 6 stanowisk, kazde do 1,2 MW. Vernon lezy w strefie przemyslowej na poludniowy wschod od centrum Los Angeles — magazyny i ruch z portow LA i Long Beach." },
      { type: "img", src: "/img/inline-semi.jpg", alt: "Tesla Semi na autostradzie", caption: "Vernon lezy w korytarzu towarowym portow Los Angeles i Long Beach." },
      { type: "h2", text: "Co juz dziala" },
      { type: "p", text: "Pierwszy pelnoskalowy publiczny Megacharger Tesla otworzyla w lipcu 2026 w Bloomington (tez Kalifornia). Rowniez 6 stanowisk i 1,2 MW. Bloomington i Vernon to pierwsza pelna konfiguracja 1,2 MW dla wszystkich klientow Semi." },
      { type: "h2", text: "W budowie i w planach" },
      { type: "ul", items: ["Texas — Laredo, Houston, Dallas, Irving, Midland, San Antonio", "Nevada — Las Vegas", "Georgia — Conley", "Floryda — Fort Pierce", "Michigan — Detroit, etap survey"] },
      { type: "p", text: "Tesla celuje w korytarze towarowe. Wczesniejsze mapy: ponad 60 lokalizacji w USA, najwiecej w Teksasie i Kalifornii." },
      { type: "h2", text: "Dlaczego to wazne" },
      { type: "img", src: "/img/cover-megacharger.jpg", alt: "Tesla Semi przy Megachargerze", caption: "Semi Long Range: ok. 60% zasiegu w 30 minut przy 1,2 MW." },
      { type: "p", text: "1,2 MW pozwala Semi Long Range uzupelnic ok. 60% zasiegu w 30 minut. Vernon i Bloomington: najpierw wezly logistyczne, potem reszta kraju." },
    ],
  },
{
    slug: "grok-bot-agents-jak-zautomatyzowac-zycie-w-10-krokach-pelny-tutorial",
    kicker: "xAI",
    topic: "xai",
    title: "Grok Bot Agents: 10 krokow, pelny tutorial",
    excerpt: "Od instalacji Chiefa do zespolu specjalistow, ktorzy przekazują sobie prace i wolaja Cie tylko przy decyzji.",
    date: "20 sierpnia 2026",
    isoDate: "2026-08-20",
    img: "/img/grok-bot.jpg",
    body: [
      { type: "p", text: "Kazde narzedzie AI, ktorego do tej pory uzywales, czeka na Ciebie. Otwierasz, pytasz, zamykasz. Praca zostaje w Twoich rekach." },
      { type: "p", text: "Grok Bot odwraca uklad. Bot dostaje komputer w chmurze, loguje sie do Twoich narzedzi i pracuje, gdy zamkniesz laptopa. Przestajesz promptowac — zaczynasz delegowac." },
      { type: "img", src: "/img/inline-desk.jpg", alt: "Stanowisko pracy z dwoma monitorami", caption: "Bot dostaje komputer i narzedzia. Ty zostawiasz decyzje." },
      { type: "h2", text: "01. Zainstaluj i poznaj Chiefa" },
      { type: "p", text: "To aplikacja desktopowa (macOS), nie zakladka. Logujesz sie kontem Grok lub Cursor. Punkt startowy: bot ogolny — Chief. Nie robi wszystkiego. Koordynuje, gdy nie wiesz, kto ma przyjac zadanie." },
      { type: "h2", text: "02. Daj mu stanowisko, nie prompt" },
      { type: "p", text: "Prompt to prosba. Bot to rola: Inbox Manager, Expense Manager, Talent Scout, Sales Outbound. Karta rol jak brief dla nowego pracownika." },
      { type: "h2", text: "03. Podlacz narzedzia raz" },
      { type: "p", text: "Integracje (Notion, Slack, Drive, Browserbase, Composio) sa na poziomie konta. Podlaczysz Gmaila raz — kazdy kolejny bot go widzi." },
      { type: "h2", text: "04. Przekaz logowanie, nie wklejaj hasla" },
      { type: "p", text: "Bot jedzie w chmurowej przegladarce do sciany logowania, oddaje Ci ekran, Ty sie logujesz, klikasz done. Dostaje sesje, nie sekret." },
      { type: "h2", text: "05-10. Workflow, routine, specjalisci, group chat, zatwierdzenia, przeglad" },
      { type: "p", text: "Nagraj workflow, ustaw routine, dziel boty wedlug dziedziny, wrzuc ich do group chatu, parkuj nieodwracalne akcje do zatwierdzenia, raz w tygodniu sprawdz wyniki." },
      { type: "p", text: "Przestajesz byc tym, kto klika. Umiejetnosc to juz nie jak sformulowac, tylko co deleguje i gdzie konczy sie wladza bota." },
    ],
  },
{
    slug: "czy-grok-jest-niedowartosciowany",
    kicker: "xAI",
    topic: "xai",
    title: "Czy Grok jest niedowartosciowany?",
    excerpt: "Czesc AI wewnatrz SpaceX wciaz jest niedoszacowana, jesli Grok dalej bedzie pial sie w rankingach.",
    date: "19 sierpnia 2026",
    isoDate: "2026-08-19",
    img: "/img/grok-chart.jpg",
    contain: true,
    body: [
      { type: "p", text: "Czesc AI wewnatrz SpaceX jest wciaz niedowartosciowana, jesli Grok bedzie dalej piac sie w rankingach." },
      { type: "p", text: "Sam Grok na poziomie Claude nie jest jeszcze aktywem wartym 2 biliony dolarow, ale kierunek tej tezy jest wlasciwy." },
      { type: "p", text: "Anthropic jest obecnie wyceniany prywatnie na okolo 965 mld dolarow. Jesli Grok domknie luke w wydajnosc, pozostajac tanszy w inference, logika ekonomiczna zaczyna sie zmieniac." },
      { type: "p", text: "xAI zostalo wycenione na mniej wiecej 230-250 mld dolarow w momencie, gdy SpaceX je przejmowal." },
      { type: "ul", items: ["wydajnosc bliska czolowce", "nizsze koszty inference", "dystrybucja przez X oraz szerszy stack SpaceX"] },
      { type: "img", src: "/img/inline-colossus.jpg", alt: "Superkomputer Colossus xAI", caption: "Wycena Groka siedzi w Colossusie, X i tanim inference." },
    ],
  },
{
    slug: "grok-boty-ktore-ustawisz-jednym-promptem",
    kicker: "xAI",
    topic: "xai",
    title: "Grok Boty, ktore ustawisz jednym promptem",
    excerpt: "Bot Directory to katalog gotowych rol. Kopiujesz prompt, wklejasz do Grok Bota i masz stanowisko w kilka minut.",
    date: "19 sierpnia 2026",
    isoDate: "2026-08-19",
    img: "/img/grok-bot.jpg",
    body: [
      { type: "h2", text: "Bot Directory" },
      { type: "p", text: "17 sierpnia 2026 pojawil sie Bot Directory (botdirectory.ai) — open-source katalog gotowych promptow do Grok Botow." },
      { type: "img", src: "/img/inline-desk.jpg", alt: "Biurko do pracy z agentami", caption: "Kopiujesz prompt z katalogu, wklejasz, podlaczasz tylko potrzebne narzedzia." },
      { type: "p", text: "Zacznij od konkretnego problemu, nie od listy botow. Skopiuj caly prompt i daj go Grok Botowi jako pierwsze zadanie." },
      { type: "p", text: "Katalog rozwiazuje najwiekszy problem poczatkujacych: od czego zaczac i jak napisac dobry opis roli." },
    ],
  },
{
    slug: "grok-bot-zbuduj-swoja-firme-ai",
    kicker: "xAI",
    topic: "xai",
    title: "Grok Bot — zbuduj swoja firme AI",
    excerpt: "Nie kolejny czat. Boty z tozsamoscia, pamiecia i prawdziwym komputerem w chmurze, ktore pracuja, gdy zamkniesz laptopa.",
    date: "17 sierpnia 2026",
    isoDate: "2026-08-17",
    img: "/img/grok-bot.jpg",
    body: [
      { type: "p", text: "Grok Bot to nowa funkcja od xAI (early beta od sierpnia 2026), ktora pozwala tworzyc AI-wspolpracownikow. Kazdy bot dostaje wlasna tozsamosc, pamiec robocza i dostep do prawdziwego komputera w chmurze." },
      { type: "img", src: "/img/inline-desk.jpg", alt: "Rownolegle stanowiska pracy", caption: "Kilka botow, jedno srodowisko, wspoldzielone pliki i sesje." },
      { type: "h2", text: "Dlaczego to wiecej niz asystent" },
      { type: "ul", items: ["Mara — szuka klientow", "Cole — pisze wiadomosci", "Rina — grafiki", "Vince — skrzynka", "Owen — podsumowanie tygodnia"] },
      { type: "p", text: "To sposob na zamiane jednej osoby w rownolegly zespol. Zaczynasz od jednego stanowiska. Reszta narasta naturalnie." },
    ],
  },
];
