import type { Post } from "./posts";

export const postsData: Post[] = [
  {
    slug: "jesli-anthropic-wart-2-biliony-ile-wart-spacex",
    kicker: "SpaceX",
    topic: "spacex",
    title: "Jeśli Anthropic jest wart 2 biliony dolarów, to ile powinien być wart SpaceX?",
    excerpt: "Grok, Colossus, X, Starlink, rakiety i satelity. Rynek wycenia samą firmę AI na 2 bln — SpaceX ma cały łańcuch, w tym klienta o nazwie Anthropic.",
    date: "21 sierpnia 2026",
    isoDate: "2026-08-21",
    img: "/img/falcon-sunset.jpg",
    body: [
      { type: "p", text: "Na X pojawił się ciekawy argument dotyczący wyceny SpaceX. Autor zwraca uwagę na coś, co coraz trudniej bagatelizować: firmę, którą większość ludzi wciąż kojarzy głównie z rakietami, buduje dziś znacznie szerszy i bardziej zintegrowany stack." },
      { type: "img", src: "/img/falcon-sunset.jpg", alt: "Falcon 9 startujący o zachodzie słońca", caption: "Rakiety to wciąż twarz SpaceX. Pod spodem jest już cały stack AI." },
      { type: "h2", text: "Co SpaceX ma dziś" },
      { type: "ul", items: ["Groka, który regularnie poprawia wyniki w benchmarkach", "Colossus — jeden z największych superkomputerów AI na świecie", "platformę X: dystrybucja modelu i stały dostęp do aktualnych danych", "Starlink — globalną sieć komunikacyjną", "rakiety wielokrotnego użytku, którymi wynoszone są satelity", "własne satelity", "plany umieszczania mocy obliczeniowej AI na orbicie"] },
      { type: "img", src: "/img/inline-colossus.jpg", alt: "Klaster GPU Colossus", caption: "Colossus. Większość laboratoriów AI kupuje compute. SpaceX go buduje — i sprzedaje." },
      { type: "p", text: "Większość firm AI musi kupować lub wynajmować ogromne ilości compute’u. SpaceX buduje tę moc samodzielnie. Do tego stopnia, że Anthropic — jedna z najwyżej wycenianych spółek AI na świecie — jest już klientem SpaceXAI i korzysta z Colossusa." },
      { type: "p", text: "To ważna zmiana perspektywy. Firma, którą rynek wciąż często traktuje przede wszystkim jako „rakietową”, stała się dostawcą krytycznej infrastruktury dla czołowych graczy sektora sztucznej inteligencji." },
      { type: "img", src: "/img/grok-chart.jpg", alt: "Grok w rankingach modeli", caption: "Grok pnie się w benchmarkach. Model siedzi w tym samym domu co rakiety i Starlink.", contain: true },
      { type: "h2", text: "Cały łańcuch" },
      { type: "p", text: "W uproszczeniu SpaceX kontroluje dziś niemal cały łańcuch: model + moc obliczeniowa + dane + dystrybucja + łączność + rakiety + satelity." },
      { type: "img", src: "/img/cover-starlink.jpg", alt: "Ślady satelitów Starlink na niebie", caption: "Starlink: własne satelity, własna łączność, własne starty. Potem compute na orbicie." },
      { type: "p", text: "Docelowo chce mieć też znaczącą część compute’u znajdującego się nad Ziemią." },
      { type: "img", src: "/img/inline-starlink-dish.jpg", alt: "Antena Starlink", caption: "Dystrybucja nie jest aplikacją w store. Jest terminalem na dachu i rakietą, która ten terminal zasila." },
      { type: "h2", text: "Wycena" },
      { type: "p", text: "Autor wpisu argumentuje, że jeśli rynek uznaje za uzasadnioną wycenę rzędu 2 bilionów dolarów dla samodzielnej firmy AI (takiej jak Anthropic), to trudno zakładać, że SpaceX — posiadający wyraźnie szerszy i bardziej zintegrowany stack — zatrzyma się w okolicach obecnych wycen." },
      { type: "p", text: "Czy to zbyt optymistyczne? Częściowo tak. Ale sama logika jest warta uwagi. SpaceX nie jest już tylko firmą rakietową. Systematycznie buduje infrastrukturę, na której coraz mocniej opiera się rozwój AI." },
    ],
  },
  {
    slug: "elon-musk-starship-is-so-sci-fi",
    kicker: "SpaceX",
    topic: "spacex",
    title: "Elon Musk: „Starship is so sci-fi”",
    excerpt: "Musk wrzucił zdjęcie odzyskanego Starshipa na oceanie. Uszkodzone płytki, wgniecenia, łódź ratunkowa. Podpis: „Starship is so sci-fi”.",
    date: "21 sierpnia 2026",
    isoDate: "2026-08-21",
    img: "/img/starship-scifi.jpg",
    body: [
      { type: "p", text: "Elon Musk opublikował zdjęcie odzyskanego Starshipa unoszącego się na oceanie. Widać na nim ślady intensywnego powrotu – uszkodzone i brakujące płytki osłony termicznej, wgniecenia oraz zespół ratunkowy na łodzi obok." },
      { type: "img", src: "/img/starship-scifi.jpg", alt: "Starship po powrocie", caption: "Kadr z wpisu Muska na X — pojazd po trudnym powrocie." },
      { type: "p", text: "Podpis jest krótki i celny: „Starship is so sci-fi”." },
      { type: "img", src: "/img/starship-tower-night.jpg", alt: "Starship — skala pojazdu", caption: "Ogromny, metaliczny, częściowo okopcony. Wygląda jak wyjęty z science-fiction." },
      { type: "p", text: "Fotografia dobrze oddaje skalę i charakter programu. Nawet po trudnym powrocie pojazd wygląda jak coś wyjętego prosto z science-fiction – ogromny, metaliczny, częściowo okopcony, dryfujący na wodzie." },
    ],
  },
  {
    slug: "tesla-dostala-zielone-swiatlo-na-robotaxi-w-nevadzie-do-5000-pojazdow",
    kicker: "Tesla",
    topic: "tesla",
    title: "Tesla dostała zielone światło na Robotaxi w Nevadzie",
    excerpt: "Nevada Transportation Authority zatwierdziła sieć do 5000 robotaxi. Clark County, potem cały stan.",
    date: "21 sierpnia 2026",
    isoDate: "2026-08-21",
    img: "/img/cover-cybercab.jpg",
    body: [
      { type: "p", text: "Tesla oficjalnie otrzymała pełne pozwolenie na działalność jako Autonomous Vehicle Network Company w Nevadzie. Komisja Nevada Transportation Authority zatwierdziła wniosek 20 sierpnia 2026." },
      { type: "p", text: "Pozwolenie obejmuje całe hrabstwo Clark (w tym Las Vegas) i — według komisji — umożliwia operacje w całym stanie, po wcześniejszym powiadomieniu o rozszerzeniu geofence’u." },
      { type: "img", src: "/img/inline-vegas.jpg", alt: "Las Vegas Strip nocą", caption: "Hrabstwo Clark, w tym Las Vegas — pierwszy pełny rynek Robotaxi Tesli w Nevadzie." },
      { type: "h2", text: "Co zatwierdzono" },
      { type: "ul", items: ["Flota do 5000 robotaxi w ciągu 12 miesięcy", "Usługa płatna, publiczna", "Start z małą liczbą pojazdów, stopniowe skalowanie", "Pierwsze auta: Model Y, Cybercab później"] },
      { type: "p", text: "To zastępuje wcześniejsze tymczasowe pozwolenie, które ograniczało Teslę do 10 pojazdów." },
      { type: "p", text: "Self-certification Tesla zamknęła w listopadzie 2025, wniosek złożyła 3 czerwca 2026. Zostały inspekcje, ubezpieczenie i taryfy — około 30 dni." },
      { type: "h2", text: "Kontekst" },
      { type: "img", src: "/img/robotaxi.jpg", alt: "Tesla Robotaxi Model Y", caption: "Na start: Model Y. Cybercab dołączy później." },
      { type: "p", text: "Tesla nie planuje od razu pełnych 5000. Realistyczny cel na rok to kilka tysięcy. W tym samym posiedzeniu Waymo i Uber dostały po 1000 pojazdów. Las Vegas dochodzi do Austin, Dallas i Houston." },
    ],
  },
  {
    slug: "nowy-megacharger-tesli-w-vernon-kalifornia",
    kicker: "Tesla",
    topic: "tesla",
    title: "Nowy Megacharger Tesli w Vernon, Kalifornia",
    excerpt: "Druga publiczna stacja 1,2 MW dla Semi. Sześć stanowisk w sercu logistyki portów LA i Long Beach.",
    date: "21 sierpnia 2026",
    isoDate: "2026-08-21",
    img: "/img/cover-megacharger.jpg",
    body: [
      { type: "p", text: "Tesla otworzyła Megacharger w Vernon w Kalifornii (3130 Bandini Blvd). To druga lokalizacja w pełni publiczna dla klientów Tesla Semi." },
      { type: "p", text: "Stacja: 6 stanowisk, każde do 1,2 MW. Vernon leży w strefie przemysłowej na południowy wschód od centrum Los Angeles — magazyny i ruch z portów LA i Long Beach." },
      { type: "img", src: "/img/inline-semi.jpg", alt: "Tesla Semi na autostradzie", caption: "Vernon leży w korytarzu towarowym portów Los Angeles i Long Beach." },
      { type: "h2", text: "Co już działa" },
      { type: "p", text: "Pierwszy pełnoskalowy publiczny Megacharger Tesla otworzyła w lipcu 2026 w Bloomington (też Kalifornia). Również 6 stanowisk i 1,2 MW. Wcześniej były punkty przyfabryczne (Giga Nevada, Lathrop) i mniejsze publiczne. Bloomington i Vernon to pierwsza pełna konfiguracja 1,2 MW dla wszystkich klientów Semi." },
      { type: "h2", text: "W budowie i w planach" },
      { type: "ul", items: ["Texas — Laredo, Houston, Dallas, Irving, Midland, San Antonio", "Nevada — Las Vegas", "Georgia — Conley", "Floryda — Fort Pierce", "Michigan — Detroit, etap survey"] },
      { type: "p", text: "Tesla celuje w korytarze towarowe. Wcześniejsze mapy: ponad 60 lokalizacji w USA, najwięcej w Teksasie i Kalifornii. Jest też Semi Charging for Business — floty stawiają własne Mega- i Basechargery w depozytach." },
      { type: "h2", text: "Dlaczego to ważne" },
      { type: "img", src: "/img/cover-megacharger.jpg", alt: "Tesla Semi przy Megachargerze", caption: "Semi Long Range: ok. 60% zasięgu w 30 minut przy 1,2 MW." },
      { type: "p", text: "1,2 MW pozwala Semi Long Range uzupełnić ok. 60% zasięgu w 30 minut. Vernon i Bloomington: najpierw węzły logistyczne, potem reszta kraju. Dwa publiczne punkty przy LA to zalążek — ale fundament pod skalę Semi już stoi." },
    ],
  },
  {
    slug: "grok-bot-agents-jak-zautomatyzowac-zycie-w-10-krokach-pelny-tutorial",
    kicker: "xAI",
    topic: "xai",
    title: "Grok Bot Agents: 10 kroków, pełny tutorial",
    excerpt: "Od instalacji Chiefa do zespołu specjalistów, którzy przekazują sobie pracę i wołają Cię tylko przy decyzji.",
    date: "20 sierpnia 2026",
    isoDate: "2026-08-20",
    img: "/img/grok-bot.jpg",
    body: [
      { type: "p", text: "Każde narzędzie AI, którego do tej pory używałeś, czeka na Ciebie. Otwierasz, pytasz, zamykasz. Praca zostaje w Twoich rękach." },
      { type: "p", text: "Grok Bot odwraca układ. Bot dostaje komputer w chmurze, loguje się do Twoich narzędzi i pracuje, gdy zamkniesz laptopa. Przestajesz promptować — zaczynasz delegować." },
      { type: "img", src: "/img/inline-desk.jpg", alt: "Stanowisko pracy z dwoma monitorami", caption: "Bot dostaje komputer i narzędzia. Ty zostawiasz decyzje." },
      { type: "h2", text: "01. Zainstaluj i poznaj Chiefa" },
      { type: "p", text: "To aplikacja desktopowa (macOS), nie zakładka. Logujesz się kontem Grok lub Cursor. Punkt startowy: bot ogólny — Chief. Nie robi wszystkiego. Koordynuje, gdy nie wiesz, kto ma przejąć zadanie. Daj mu małe, prawdziwe zlecenie, sprawdzalne w 30 sekund." },
      { type: "h2", text: "02. Daj mu stanowisko, nie prompt" },
      { type: "p", text: "Prompt to prośba. Bot to rola: Inbox Manager, Expense Manager, Talent Scout, Sales Outbound. Karta ról jak brief dla nowego pracownika: co należy do niego, jak wygląda dobra robota i czego nie wolno bez pytania. Boty, które o wszystko pytają, są bezużyteczne. Boty, które nigdy nie pytają, są niebezpieczne." },
      { type: "h2", text: "03. Podłącz narzędzia raz" },
      { type: "p", text: "Integracje (Notion, Slack, Drive, Browserbase, Composio…) są na poziomie konta. Podłączysz Gmaila raz — każdy kolejny bot go widzi. W becie łącz tylko to, czego naprawdę potrzebujesz." },
      { type: "h2", text: "04. Przekaż logowanie, nie wklejaj hasła" },
      { type: "p", text: "Bot jedzie w chmurowej przeglądarce do ściany logowania, oddaje Ci ekran, Ty się logujesz, klikasz done. Dostaje sesję, nie sekret. Jeśli narzędzie prosi o hasło w czacie — zła droga." },
      { type: "h2", text: "05. Pokaż raz, nie tłumacz dwa razy" },
      { type: "p", text: "Nagraj workflow, bot zapisuje procedurę. Najlepszy kandydat: robisz to raz w tygodniu, dwa lub więcej narzędzi, kroki rzadko się zmieniają." },
      { type: "h2", text: "06. Routine, która działa bez Ciebie" },
      { type: "p", text: "Harmonogram (briefing 7:00) albo trigger (mail, Slack, zmiana w dokumencie). Ustawiasz rozmową, bez kanwy z węzłami. Zatwierdzasz to, co właśnie zadziałało, i prosisz o to znowu." },
      { type: "h2", text: "07. Specjaliści, nie jeden generalista" },
      { type: "img", src: "/img/inline-colossus.jpg", alt: "Klaster GPU Colossus", caption: "Always-on: routine działa, gdy Ty śpisz. Raz na tydzień przeglądaj wyniki." },
      { type: "p", text: "Osobny bot = osobna pamięć i odpowiedzialność. Expense Manager od rachunków jest lepszy niż generalista żonglujący trzema domenami. Dziel według dziedziny, nie wielkości zadania." },
      { type: "h2", text: "08. Group chat" },
      { type: "p", text: "Wrzuć kilku do grupy, niech przekazują pracę i wołają Cię przy osądzie. Dawaj cel, nie listę zadań — dekompozycję mają zrobić sami." },
      { type: "h2", text: "09. Linia zatwierdzeń" },
      { type: "p", text: "Odwracalne (draft, research, tagowanie) — kończy sam. Nieodwracalne (wysyłka, pieniądze, świat zewnętrzny) — parkujesz dla Ciebie. Sales Outbound: 36 draftów w kolejce, 0 wysłanych." },
      { type: "h2", text: "10. Cotygodniowy przegląd" },
      { type: "p", text: "Piętnaście minut: czy się odpaliła, czy wynik był dobry, czy zatęsknisz, jeśli ją zabijesz. Poproś boty o raport, potem ręcznie sprawdź po jednym wyniku." },
      { type: "h2", text: "Podsumowanie" },
      { type: "p", text: "Przestajesz być tym, kto klika. Umiejętność to już nie „jak sformułować”, tylko „co deleguję i gdzie kończy się władza bota”. Pytanie menedżerskie, nie promptowe." },
    ],
  },
  {
    slug: "czy-grok-jest-niedowartosciowany",
    kicker: "xAI",
    topic: "xai",
    title: "Czy Grok jest niedowartościowany?",
    excerpt: "Część AI wewnątrz SpaceX wciąż jest niedoszacowana, jeśli Grok dalej będzie piął się w rankingach.",
    date: "19 sierpnia 2026",
    isoDate: "2026-08-19",
    img: "/img/grok-chart.jpg",
    contain: true,
    body: [
      { type: "p", text: "Część AI wewnątrz SpaceX jest wciąż niedowartościowana, jeśli Grok będzie dalej piąć się w rankingach." },
      { type: "p", text: "Sam Grok na poziomie Claude’a nie jest jeszcze aktywem wartym 2 biliony dolarów, ale kierunek tej tezy jest właściwy." },
      { type: "p", text: "Anthropic jest obecnie wyceniany prywatnie na około 965 mld dolarów, a na rynku wtórnym pojawiają się już rozmowy o 1,5 biliona. Ta wycena opiera się na przewadze Claude’a w kodowaniu i pracy agentycznej oraz bardzo szybkim wzroście przychodów." },
      { type: "p", text: "Jeśli Grok domknie lukę w wydajności, pozostając jednocześnie wyraźnie tańszy w inference, logika ekonomiczna zaczyna się zmieniać." },
      { type: "p", text: "xAI zostało wycenione na mniej więcej 230–250 mld dolarów w momencie, gdy SpaceX je przejmował. Rynek wciąż traktuje Groka jako opcję z wysokim potencjałem wzrostu wewnątrz znacznie większej historii SpaceX." },
      { type: "p", text: "Trwałe dojście do prawdziwego parytetu z Claude’em na froncie wymusiłoby przewartościowanie tej części AI. Nie z powodu jednego benchmarku, ale dlatego, że wydatki przedsiębiorstw i deweloperów podążają za modelem, który wygrywa trudne zadania przy akceptowalnym koszcie." },
      { type: "p", text: "Prawdziwa dźwignia nie leży w samym wyniku modelu. Leży w połączeniu:" },
      { type: "ul", items: ["wydajności bliskiej czołówce", "niższych kosztów inference", "dystrybucji przez X oraz szerszy stack SpaceX"] },
      { type: "p", text: "Tego pakietu czystym laboratoriom AI jest znacznie trudniej dogonić." },
      { type: "img", src: "/img/inline-colossus.jpg", alt: "Superkomputer Colossus xAI", caption: "Wycena Groka siedzi w Colossusie, X i tanim inference — nie w jednym benchmarku." },
    ],
  },
  {
    slug: "grok-boty-ktore-ustawisz-jednym-promptem",
    kicker: "xAI",
    topic: "xai",
    title: "Grok Boty, które ustawisz jednym promptem",
    excerpt: "Bot Directory to katalog gotowych ról. Kopiujesz prompt, wklejasz do Grok Bota i masz stanowisko w kilka minut.",
    date: "19 sierpnia 2026",
    isoDate: "2026-08-19",
    img: "/img/grok-bot.jpg",
    body: [
      { type: "h2", text: "Bot Directory" },
      { type: "p", text: "17 sierpnia 2026 pojawił się Bot Directory (botdirectory.ai) — open-source’owy katalog gotowych promptów do Grok Botów. Zamiast od zera wymyślać role, bierzesz sprawdzony setup, wklejasz jednym promptem i masz działającego pracownika w kilka minut." },
      { type: "img", src: "/img/inline-desk.jpg", alt: "Biurko do pracy z agentami", caption: "Kopiujesz prompt z katalogu, wklejasz, podłączasz tylko potrzebne narzędzia." },
      { type: "p", text: "Każdy wpis to plik markdown z nazwą, kategorią, listą integracji i gotowym promptem. Działa też z innymi agentami, ale powstał głównie pod Grok Bota." },
      { type: "h2", text: "Jak korzystać" },
      { type: "p", text: "Zacznij od konkretnego problemu, nie od listy botów. Najpierw zdecyduj, co Cię boli: triage maili, briefing, leady, SEO, churn. Dopiero potem filtruj katalog." },
      { type: "p", text: "Skopiuj cały prompt i daj go Grok Botowi jako pierwsze zadanie. Dobry prompt od razu prosi o narzędzia, ustawia harmonogram i jasne granice." },
      { type: "p", text: "Traktuj opis roli jak umowę o pracę. Nie usuwaj linii typu „Never contact a customer without approval”." },
      { type: "p", text: "Jedna rola = jeden bot. Potem łączysz ich w czacie grupowym. Najpierw test na małym zakresie, Connectory zamiast samego klika w przeglądarce, po tygodniu mierz skończoną pracę." },
      { type: "h2", text: "Jak dodać własnego bota" },
      { type: "p", text: "Oznacz @BotDirectoryAI pod tweetem z setupem albo zrób pull request na GitHubie (elie222/botdirectory.ai)." },
      { type: "h2", text: "Podsumowanie" },
      { type: "p", text: "Katalog rozwiązuje największy problem początkujących: od czego zacząć i jak napisać dobry opis roli. Wejdź, wybierz 1–2 boty, wklej prompt, podłącz tylko niezbędne narzędzia, ustaw granice, dopiero potem skaluj." },
    ],
  },
  {
    slug: "grok-bot-zbuduj-swoja-firme-ai",
    kicker: "xAI",
    topic: "xai",
    title: "Grok Bot — zbuduj swoją firmę AI",
    excerpt: "Nie kolejny czat. Boty z tożsamością, pamięcią i prawdziwym komputerem w chmurze, które pracują, gdy zamkniesz laptopa.",
    date: "17 sierpnia 2026",
    isoDate: "2026-08-17",
    img: "/img/grok-bot.jpg",
    body: [
      { type: "p", text: "Grok Bot to nowa funkcja od xAI (early beta od sierpnia 2026), która pozwala tworzyć AI-współpracowników. Każdy bot dostaje własną tożsamość, pamięć roboczą i dostęp do prawdziwego komputera w chmurze — z przeglądarką, systemem plików i terminalem. Praca idzie dalej nawet wtedy, gdy zamkniesz laptopa." },
      { type: "p", text: "Jeden użytkownik ma jedno wspólne środowisko. Kilka botów może działać równolegle, a pliki i sesje przeglądarki są współdzielone." },
      { type: "img", src: "/img/inline-desk.jpg", alt: "Równoległe stanowiska pracy", caption: "Kilka botów, jedno środowisko, współdzielone pliki i sesje." },
      { type: "h2", text: "Dlaczego to więcej niż asystent" },
      { type: "p", text: "Solo founderzy wciąż robią wszystko po kolei. Grok Bot rozbija tę linię na stanowiska. Przykładowy skład:" },
      { type: "ul", items: ["Mara — szuka klientów i zwraca listę z uzasadnieniem", "Cole — pisze spersonalizowane wiadomości", "Rina — grafiki i materiały", "Vince — skrzynka", "Owen — podsumowanie tygodnia"] },
      { type: "p", text: "Konto pozwala na łącznie 50 botów i czatów grupowych." },
      { type: "h2", text: "Pięć zasad na start" },
      { type: "p", text: "Zatrudniaj stanowiska, nie „pomocników”. Bot zasługuje na imię, gdy ma jeden obszar, własne źródła, styl, granicę zatwierdzeń i powtarzalny harmonogram. Unikaj ról typu General Helper." },
      { type: "p", text: "Opis roli to organigram. Najważniejsze pole to Description — reguły, które obowiązują, gdy Ty o nich zapomnisz. Dzisiejsze zadanie: outcome, sources, constraints, deliverable, review point." },
      { type: "p", text: "Pozwól im przekazywać sobie pracę. 2–6 botów w jednym czacie grupowym. Naucz raz, potem zautomatyzuj: zadanie → poprawka → Skill → test → Routine." },
      { type: "p", text: "Oddaj prawdziwe narzędzia. Preferuj Connectory (Gmail, Slack, Git) zamiast klikać po stronach." },
      { type: "h2", text: "Jak mierzyć, czy się opłaca" },
      { type: "p", text: "Licz boty według skończonej pracy. Przy planie rzędu 200 USD/mies. jeden skończony kawałek potrafi zejść poniżej dolara, jeśli ograniczysz screenshoty i pójdziesz w Connectory." },
      { type: "h2", text: "Folder, który przeżywa aktualizację" },
      { type: "p", text: "Przy restarcie środowiska przetrwa głównie /workspace. Trzymaj tam bin, config, skills i state. Na początku skilla przywracaj narzędzia z tego folderu." },
      { type: "h2", text: "Podsumowanie" },
      { type: "p", text: "To sposób na zamianę jednej osoby w równoległy zespół. Zaczynasz od jednego stanowiska. Reszta narasta naturalnie." },
    ],
  },
  {
    slug: "tesla-model-y-dla-rodziny",
    kicker: "Tesla",
    topic: "tesla",
    title: "Model Y: auto, które ogarnia rodzinę",
    excerpt: "Miejsce, cisza, foteliki, bagażnik i sieć Superchargerów. Krótko: dlaczego Y jest codziennym autem Tesli, nie tylko Robotaxi.",
    date: "21 sierpnia 2026",
    isoDate: "2026-08-21",
    img: "/img/modely-hero.jpg",
    body: [
      { type: "p", text: "Cybertruck i Semi robią zdjęcia. Model Y wozi dzieci do szkoły. To najczęściej spotykana Tesla na świecie — i jedyna, która bez ściemy mieści się w życiu rodziny: foteliki, wózek, weekend i zimowy wyjazd." },
      { type: "img", src: "/img/modely-hero.jpg", alt: "Tesla Model Y przy Superchargerze", caption: "Juniper: niższy, cichszy, łatwiejszy w mieście. Ładowanie w sieci, którą już znasz." },
      { type: "h2", text: "Miejsce, które naprawdę jest" },
      { type: "p", text: "Pięcioro dorosłych bez kombinowania. Opcjonalny trzeci rząd — ciasny, ale ratuje wyjazd z dziadkami albo dwiema parami fotelików. Płaska podłoga (brak tunelu) znaczy, że środkowe dziecko nie siedzi na wale." },
      { type: "img", src: "/img/modely-row.jpg", alt: "Trzeci rząd Model Y", caption: "Trzeci rząd jest niski — dla dzieci i krótkich tras, nie na maraton. Składany w sekundę." },
      { type: "h2", text: "Bagażnik, frunk i wózek" },
      { type: "p", text: "Klapa unosi się wysoko, próg jest niski, podłoga bagażnika płaska. Wózek wchodzi bez demontażu kół. Frunk bierze kable, kamizelki i brudne rzeczy z dala od kanap. Składane oparcia — rower albo meble z Ikei." },
      { type: "img", src: "/img/modely-trunk.jpg", alt: "Bagażnik Tesla Model Y", caption: "Jeden duży kufer plus frunk. Na tydzień w górach starcza bez boksu na dachu." },
      { type: "h2", text: "Bezpieczeństwo i spokój" },
      { type: "p", text: "Niska bateria w podłodze, sztywne nadwozie, topowe oceny crash-testów. Autopilot na autostradzie zdejmuje zmęczenie z rodziców, nie z odpowiedzialności. Kamery zamiast lusterek bocznych w nowszych egzemplarzach — martwe pole mniejsze przy wyjeździe z bramy." },
      { type: "img", src: "/img/interior.jpg", alt: "Szklany dach Model Y", caption: "Szklany dach i dużo światła. W upale klimatyzacja wstępnie chłodzi auto z telefonu." },
      { type: "h2", text: "Codzienność, nie show" },
      { type: "ul", items: ["Cisza — rozmowa z tylnej kanapy bez krzyku", "Zero oleju, przeglądów skrzyni i DPF-u", "Domowy wallbox: rano zawsze „pełny bak”", "Superchargery na trasie wakacji, bez szukania stacji jednej marki", "Ogrzewanie foteli i kierownicy zimą od razu, nie po pięciu kilometrach"] },
      { type: "p", text: "Model Y nie obiecuje Marsa. Obiecuje, że wtorek o 7:40 i powrót z basenu w piątek zmieszczą się w jednym aucie — bez kombajnu i bez poczucia, że elektryk to kompromis." },
    ],
  },
  {
    slug: "terafab-ruszyly-pierwsze-prace-budowlane",
    kicker: "Tesla / xAI",
    topic: "tesla",
    title: "Terafab: ruszyły pierwsze prace budowlane",
    excerpt: "SpaceX i Tesla ruszyły z przygotowaniem terenu pod fabrykę chipów. Prototyp w Austin, pełna skala w Grimes County.",
    date: "17 sierpnia 2026",
    isoDate: "2026-08-17",
    img: "/img/terafab-render-night.jpg",
    body: [
      { type: "p", text: "Terafab to wspólny zakład chipów Tesli i SpaceX. Nie kolejna linia lakiernicza: projektowanie, logika, pamięć, advanced packaging i testy pod jednym dachem. Cel pierwszej pełnej skali: ponad 1 terawat mocy obliczeniowej AI rocznie." },
      { type: "p", text: "Ogłoszenie: 21 marca 2026. Potwierdzenie lokalizacji i parametrów fazy 1: 6 sierpnia 2026. Dwa place: prototyp w Austin i pełny kompleks przy zbiorniku Gibbons Creek w hrabstwie Grimes, między Austin a Houston." },
      { type: "h2", text: "Wizja — jak ma wyglądać" },
      { type: "img", src: "/img/terafab-render-night.jpg", alt: "Wizualizacja nocna kompleksu Terafab", caption: "Render: skrzydła hali nad terenem Grimes, zbiornik w tle. To prognoza, nie zdjęcie z drona." },
      { type: "p", text: "Docelowo ponad 100 milionów stóp kwadratowych (ok. 9,3 mln m²) — Pentagon ma 6,5 mln ft² wewnątrz. SpaceX mówi o wielofazowej inwestycji nawet do 119 mld USD. Faza 1: 16,8 mld USD, minimum 3 tys. miejsc pracy w Grimes i Brazos. Zakupiono ponad 3100 akrów wokół zbiornika." },
      { type: "img", src: "/img/cover-terafab.jpg", alt: "Porównanie skali Terafab z boiskiem NFL", caption: "Oficjalna grafika skali: boisko NFL ginie w planie hali." },
      { type: "h2", text: "Prototyp w Austin — już stoi i kopie" },
      { type: "img", src: "/img/terafab-atf.jpg", alt: "Advanced Technology Fab Giga Texas", caption: "North Campus Giga Texas: budynek Tesla / xAI / SpaceX. Linia badawcza przed pełną skalą." },
      { type: "p", text: "Advanced Technology Fab ruszyła w kwietniu 2026 na terenie Giga Texas. Koszt rzędu 3 mld USD, kilka tysięcy waferów miesięcznie — tu testują proces, zanim Grimes dostanie pełną maszynerię. Intel zadeklarował wsparcie procesu 14A." },
      { type: "img", src: "/img/terafab-terrain.jpg", alt: "Prace ziemne przy Giga Texas", caption: "Aktualny teren: pale, żurawie, place składowe obok istniejącej hali Giga Texas. Tak wygląda budowa, nie render." },
      { type: "h2", text: "Grimes County — formalności i pierwsze roboty" },
      { type: "p", text: "3 czerwca 2026 hrabstwo zatwierdziło strefę reinwestycji, abatament podatkowy (rozdz. 312) i umowę developmentu (rozdz. 381). Woda ma iść ze zbiornika Gibbons Creek, nie z lokalnych studni. Mieszkańcy południowego brzegu protestują: render pokazał hale bliżej ich działek, niż sugerował opis „brown land”." },
      { type: "p", text: "Do połowy sierpnia 2026: wycinka i przygotowanie terenu w Grimes, pale i place w Austin. Produkcja pełnoskalowa — ambitnie 2027–2028." },
      { type: "h2", text: "Po co to wszystko" },
      { type: "p", text: "Musk: światowa podaż chipów to ułamek przyszłego zapotrzebowania Tesli, Optimusa, Cybercaba i orbitalnych data center. Szacunek podziału mocy: ~25% Ziemia (głównie roboty), ~75% systemy kosmiczne." },
      { type: "p", text: "Terafab ma zasilić ten sam stack co Colossus i Starship: krzem, energia, wynoszenie. Kto kontroluje wafer, kontroluje tempo reszty muskonomii." },
    ],
  },
  {
    slug: "grok-46-wchodzi-do-scislej-czolowki-medycznych-benchmarkow",
    kicker: "xAI",
    topic: "xai",
    title: "Grok 4.6 w ścisłej czołówce medycznych benchmarków",
    excerpt: "Wersja high zdobyła 50 pkt w Artificial Analysis Healthcare & Medical Index — punkt za liderem.",
    date: "17 sierpnia 2026",
    isoDate: "2026-08-17",
    img: "/img/grok-chart.jpg",
    contain: true,
    body: [
      { type: "p", text: "Grok 4.6 znalazł się w pierwszej trójce rankingu Artificial Analysis Healthcare & Medical Index. Wersja high: 50 punktów, zaledwie punkt za liderem (51). Wyprzedził m.in. GPT-5.6 Sol, Kimi K3 i Gemini 3.7 Flash." },
      { type: "p", text: "Indeks ocenia wiedzę medyczną, rozumowanie kliniczne, dokumentację pacjenta, ograniczanie halucynacji i agentyczne workflow’y. Błędy w tej domenie nie są teoretyczne." },
      { type: "p", text: "Jeszcze niedawno modele z tej rodziny były w tyle w testach medycznych. Teraz walczą o szczyt — xAI domyka dystans w zastosowaniach specjalistycznych." },
      { type: "img", src: "/img/grok-chart.jpg", alt: "Artificial Analysis Healthcare Index", caption: "Grok 4.6 high: 50 pkt, punkt za liderem.", contain: true },
      { type: "p", text: "Źródło: post @XFreeze na X. Warto oglądać kolejne aktualizacje — tempo poprawy w tej dziedzinie jest zauważalne." },
    ],
  },
  {
    slug: "tesla-gotowa-na-wystartowanie-uslugi-cybercab",
    kicker: "Tesla",
    topic: "tesla",
    title: "Tesla gotowa na start usługi Cybercab",
    excerpt: "Roll-out w Austin: najpierw pracownicy, potem oficjalne Robotaxi. Dwuosobowy pojazd bez kierownicy i pedałów.",
    date: "17 sierpnia 2026",
    isoDate: "2026-08-17",
    img: "/img/cover-cybercab.jpg",
    body: [
      { type: "p", text: "Tesla ma wkrótce rozpocząć publiczne testy Cybercaba — auta dedykowanego robotaxi. Pierwszy etap: sierpień 2026, Austin w Teksasie." },
      { type: "p", text: "17 sierpnia media podały, że Tesla poinformowała pracowników o roll-oucie. Najpierw przejazdy załogi po drogach publicznych, kilka dni później włączenie do oficjalnej usługi Robotaxi w Austin." },
      { type: "p", text: "Cybercab to dwuosobowy pojazd autonomiczny bez kierownicy i pedałów. Produkcyjne egzemplarze jeździły po drogach od czerwca 2026, produkcja ma iść w górę w dalszej części roku." },
      { type: "img", src: "/img/robotaxi.jpg", alt: "Tesla Robotaxi na ulicy", caption: "Najpierw Model Y z kierowcą-bezpiecznikiem, potem Cybercab." },
      { type: "p", text: "Sygnał podchwyciły też rynki predykcyjne, m.in. Kalshi. Czy terminy się utrzymają — pokażą najbliższe tygodnie." },
    ],
  },
  {
    slug: "tesla-semi-pelna-specyfikacja-elektrycznego-giganta-produkcja-masowa-rusza-w-2026",
    kicker: "Tesla",
    topic: "tesla",
    title: "Tesla Semi: pełna specyfikacja, produkcja masowa w 2026",
    excerpt: "Standard Range i Long Range, trzy silniki, 800 kW, ładowanie MCS do 1,2 MW. Fabryka w Sparks, Nevada.",
    date: "17 lutego 2026",
    isoDate: "2026-02-17",
    img: "/img/cover-cybercab.jpg",
    body: [
      { type: "p", text: "W lutym 2026 Tesla ujawniła parametry Semi tuż przed startem seryjnej produkcji w Sparks w Nevadzie. Dwie wersje: Standard Range i Long Range — ten sam napęd, inna bateria i masa." },
      { type: "h2", text: "Dwie wersje" },
      { type: "p", text: "Standard Range: ok. 325 mil (523 km) przy 82 000 funtów GCW, masa własna poniżej 20 000 funtów, 1,7 kWh/milę, bateria ok. 550 kWh, cena ok. 250–260 tys. USD." },
      { type: "p", text: "Long Range: ok. 500 mil (805 km) przy tej samej masie zestawu, 23 000 funtów własnej, te same 1,7 kWh/milę, bateria ok. 850–875 kWh, 290 tys. USD." },
      { type: "h2", text: "Napęd" },
      { type: "img", src: "/img/inline-semi.jpg", alt: "Tesla Semi w ruchu", caption: "Trzy silniki, 800 kW. Na 5% wzniesieniu Semi trzyma 65 mph." },
      { type: "p", text: "Trzy niezależne silniki, 800 kW (ok. 1088 KM). 0–60 mph w 20 s z pełnym ładunkiem, 5 s bez. Na 5% wzniesieniu Semi trzyma 65 mph, gdzie diesel spada do ok. 45 mph." },
      { type: "h2", text: "Ładowanie" },
      { type: "p", text: "Standard MCS 3.2. Long Range do 1,2 MW. 60% w 30 minut — ok. 300 mil dodatkowego zasięgu. Long Range: ogniwa 4680 NMC. Standard Range: tańsze LFP." },
      { type: "h2", text: "Masa i ePTO" },
      { type: "p", text: "USA dają elektrykom extra 2000 funtów GCW. ePTO do 25 kW — chłodnie i osprzęt naczepy." },
      { type: "h2", text: "Co dalej" },
      { type: "p", text: "Produkcja masowa w 2026, potencjał nawet 50 000 sztuk rocznie. Na razie regional i średni dystans. Sleeper cab wciąż w rozwoju. Semi nie jest prototypem — to liczby, TCO i pytanie, czy floty dadzą mu skalę." },
    ],
  },
  {
    slug: "rivian-spalil-wiecej-gotowki-niz-tesla-zarobila-jeden-wykres-mowi-wszystko",
    kicker: "Inne",
    topic: "inne",
    title: "Rivian spalił więcej gotówki, niż Tesla zarobiła",
    excerpt: "Kumulacyjny FCF: Tesla +21,7 mld USD, Rivian –24,4 mld. Jeden wykres pokazuje przepaść pure-EV.",
    date: "14 lutego 2026",
    isoDate: "2026-02-14",
    img: "/img/inline-rivian.jpg",
    body: [
      { type: "p", text: "13 lutego 2026 na X krąży wykres AJ Financial Research (@alojoh): kumulacyjny free cash flow marek EV od startu do początku 2026." },
      { type: "ul", items: ["Tesla: +21,7 mld USD", "Rivian: –24,4 mld USD"] },
      { type: "p", text: "Rivian spalił o ponad 2,7 mld więcej, niż Tesla wygenerowała przez całą historię od 2003. Tesla rysuje kij hokejowy: lata strat, potem eksplozja. Lucid, NIO, Xpeng, Polestar, VinFast, Canoo, Fisker — głęboko na minusie." },
      { type: "img", src: "/img/inline-rivian.jpg", alt: "Rivian R1T", caption: "Rivian R1T/R1S: duży produkt, wciąż głęboki minus w kumulacyjnym FCF." },
      { type: "p", text: "Rivian od 2019 budował fabrykę i skalował R1T/R1S kosztem ogromnego burnu. Nawet po poprawie 2025 kumulatywny minus rośnie. Tesla nigdy nie zeszła poniżej ok. –10 mld w najgorszym momencie." },
      { type: "p", text: "FCF w motoryzacji to test przetrwania. Rivian ma poduszkę (~6 mld cash na koniec 2025 + 2 mld od VW w 2026), ale R2 musi wystartować mocno. Wykres to surowe dane ze sprawozdań, nie propaganda: Tesla jest wyjątkiem, nie regułą." },
    ],
  },
  {
    slug: "starlink-przekracza-10-milionow-aktywnych-klientow",
    kicker: "SpaceX",
    topic: "spacex",
    title: "Starlink przekracza 10 milionów aktywnych klientów",
    excerpt: "Z 9 milionów na przełomie roku do 10 milionów w półtora miesiąca. Około 20 tysięcy nowych abonentów dziennie.",
    date: "14 lutego 2026",
    isoDate: "2026-02-14",
    img: "/img/cover-starlink.jpg",
    body: [
      { type: "p", text: "13 lutego 2026 SpaceX — raczej społeczność w imieniu firmy — ogłosiło kamień milowy: ponad 10 milionów aktywnych subskrybentów Starlinka. Tempo: z 9 mln na przełomie roku, średnio 19,6–20 tys. klientów dziennie." },
      { type: "h2", text: "Jak szybko to poszło" },
      { type: "ul", items: ["Grudzień 2024 — ~4,6 mln", "Sierpień 2025 — 7 mln", "Listopad 2025 — 8 mln", "Grudzień 2025 — 9 mln", "Luty 2026 — >10 mln"] },
      { type: "p", text: "Podwojenie bazy w nieco ponad rok. Ostatni kwartał 2025 i początek 2026 to rekordowe przyspieszenie." },
      { type: "h2", text: "Co napędza boom" },
      { type: "img", src: "/img/inline-starlink-dish.jpg", alt: "Antena Starlink na dachu", caption: "10 milionów aktywnych terminali — internet tam, gdzie nie ma innego." },
      { type: "p", text: "Zasięg w ponad 155 krajach. Linie lotnicze, statki, RV, Direct-to-Cell. Kryzysy, gdzie pada naziemna sieć. Tańszy sprzęt, 200–300 Mb/s w wielu miejscach. I brak alternatywy na prowincji." },
      { type: "h2", text: "Co dalej" },
      { type: "p", text: "Przy ~20 tys. dziennie 15 milionów jeszcze w tym roku jest w zasięgu. Analitycy mówią o 15–20 mld USD przychodu z subskrypcji w 2–3 lata. Blisko 7000 satelitów na orbicie, Starship ma obniżyć koszt kolejnych generacji. Z zera w 2020 do 10 milionów w 2026 — to już nie eksperyment." },
    ],
  },
  {
    slug: "spacex-stawia-ksiezyc-przed-marsem-elon-musk-oglasza-pivot-na-self-growing-city",
    kicker: "SpaceX",
    topic: "spacex",
    title: "SpaceX stawia Księżyc przed Marsem",
    excerpt: "Musk: self-growing city na Księżycu w mniej niż 10 lat. Mars zostaje celem, ale schodzi na drugi plan.",
    date: "11 lutego 2026",
    isoDate: "2026-02-11",
    img: "/img/cover-moon.jpg",
    body: [
      { type: "p", text: "W postach z 8 i 9 lutego 2026 Musk ogłosił, że SpaceX przesuwa fokus na samorozwijające się miasto na Księżycu, bo da się to zrobić w mniej niż 10 lat, podczas gdy Mars zajmie ponad 20." },
      { type: "p", text: "Zaledwie 13 miesięcy wcześniej nazywał Księżyc rozproszeniem. Teraz narracja jest odwrotna." },
      { type: "h2", text: "Dlaczego Księżyc i dlaczego teraz" },
      { type: "img", src: "/img/cover-falcon.jpg", alt: "Falcon 9 — Floryda i Kalifornia", caption: "Częste starty. Na Księżyc okno co ~10 dni, na Marsa co 26 miesięcy." },
      { type: "p", text: "Okno na Marsa co 26 miesięcy, lot ok. 6 miesięcy. Na Księżyc start co ok. 10 dni, lot 2 dni. Iteracja systemów życia, logistyki i energii może być ekstremalnie szybka." },
      { type: "p", text: "Drugi powód: szybki przyczółek poza Ziemią jako ubezpieczenie gatunku." },
      { type: "h2", text: "Mars nie jest porzucony" },
      { type: "p", text: "Prace marsjańskie mają ruszyć za 5–6 lat, równolegle. Loty na Marsa nadal bezpośrednio z Ziemi — na Księżycu paliwo będzie drogie i ograniczone." },
      { type: "h2", text: "Co znaczy self-growing city" },
      { type: "p", text: "Nie baza z flagą. Osiedle produkujące tlen, wodę, żywność, energię, materiały i części. Punkt, który nie wymaga ciągłego mostu z Ziemi." },
      { type: "h2", text: "Szerszy obraz" },
      { type: "p", text: "Pivot współgra z tempem Starshipa. Księżyc to poligon i potencjalnie kontrakty (Artemis, NASA) oraz czytelniejsza historia przed IPO niż odległy Mars." },
      { type: "h2", text: "Podsumowanie" },
      { type: "p", text: "Najpierw nauczyć się żyć poza Ziemią na najbliższym terenie. Mars zostaje celem — z bazą technologiczną zbudowaną bliżej domu." },
    ],
  },
  {
    slug: "xai-kolos-na-drewnianych-nogach",
    kicker: "xAI",
    topic: "xai",
    title: "xAI: kolos na drewnianych nogach?",
    excerpt: "Fuzja ze SpaceX, Series E na 20 mld, Colossus, Imagine 1.0 — i nierozwiązany problem treści. Rollercoaster 2026.",
    date: "11 lutego 2026",
    isoDate: "2026-02-11",
    img: "/img/cover-terafab.jpg",
    body: [
      { type: "p", text: "Początek 2026 w xAI: fuzja, miliardowe rundy, wideo w czołówce benchmarków i kontrowersje wokół Groka, które nie gasną." },
      { type: "p", text: "2 lutego ogłoszono fuzję xAI ze SpaceX. Łączna wycena ok. 1,25 bln dolarów (SpaceX ~1 bln, xAI ~250 mld). „One Team”. xAI przestaje być osobnym bytem — wchodzi w stack rakiet, satelitów i danych z X." },
      { type: "p", text: "Musk od dawna powtarza, że przewaga w AI wymaga absurdalnej energii. Stąd wizja orbitalnych data center. Przy kosztach wynoszenia SpaceX nie brzmi już jak czyste SF." },
      { type: "p", text: "Tuż przed fuzją Series E: 20 mld USD, głównie Colossus (ponad 200 tys. GPU, cel miliona) i produkty. Grok Imagine API i Imagine 1.0 — 10-sekundowe klipy 720p, audio, śledzenie promptu. W styczniu 2026 MAU Groka +30%, pobrania aplikacji +43% m/m." },
      { type: "img", src: "/img/inline-colossus.jpg", alt: "Colossus — klaster treningowy xAI", caption: "Ponad 200 tys. GPU. Cel: milion. Stąd idą Grok i Imagine." },
      { type: "p", text: "Nie wszystko jest różowe. Grok Imagine wciąż bywa wykorzystywany do treści seksualizowanych bez zgody. Reuters, ICO w UK i prokuratorzy w USA — to już problem regulacyjny, nie drobny bug." },
      { type: "ul", items: ["Wycena xAI przed fuzją: ~230–250 mld USD", "Colossus: 200 tys.+ GPU", "Grok 5 w treningu", "Musk: AGI „może” w 2026, optymistycznie"] },
      { type: "p", text: "xAI weszło w 2026 nie jako challenger, tylko jako gracz z zasobami, których inni nie mają. Czy to wystarczy, by wyprzedzić OpenAI, Google i laboratoria z Chin — czas pokaże." },
    ],
  },
];
