/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as TematyIndexRouteImport } from './routes/tematy.index'
import { Route as TematyTopicRouteImport } from './routes/tematy.$topic'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as HubyIndexRouteImport } from './routes/huby.index'
import { Route as HubySlugRouteImport } from './routes/huby.$slug'
import { Route as SzukajRouteImport } from './routes/szukaj'
import { Route as ArchiwumIndexRouteImport } from './routes/archiwum.index'
import { Route as ArchiwumYearMonthRouteImport } from './routes/archiwum.$year.$month'
import { Route as OSerwisieRouteImport } from './routes/o-serwisie'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TematyIndexRoute = TematyIndexRouteImport.update({
  id: '/tematy/',
  path: '/tematy/',
  getParentRoute: () => rootRouteImport,
} as any)
const TematyTopicRoute = TematyTopicRouteImport.update({
  id: '/tematy/$topic',
  path: '/tematy/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HubyIndexRoute = HubyIndexRouteImport.update({
  id: '/huby/',
  path: '/huby/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubySlugRoute = HubySlugRouteImport.update({
  id: '/huby/$slug',
  path: '/huby/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SzukajRoute = SzukajRouteImport.update({
  id: '/szukaj',
  path: '/szukaj',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiwumIndexRoute = ArchiwumIndexRouteImport.update({
  id: '/archiwum/',
  path: '/archiwum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiwumYearMonthRoute = ArchiwumYearMonthRouteImport.update({
  id: '/archiwum/$year/$month',
  path: '/archiwum/$year/$month',
  getParentRoute: () => rootRouteImport,
} as any)
const OSerwisieRoute = OSerwisieRouteImport.update({
  id: '/o-serwisie',
  path: '/o-serwisie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/tematy/': typeof TematyIndexRoute
  '/tematy/$topic': typeof TematyTopicRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/huby/': typeof HubyIndexRoute
  '/huby/$slug': typeof HubySlugRoute
  '/szukaj': typeof SzukajRoute
  '/archiwum/': typeof ArchiwumIndexRoute
  '/archiwum/$year/$month': typeof ArchiwumYearMonthRoute
  '/o-serwisie': typeof OSerwisieRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/tematy': typeof TematyIndexRoute
  '/tematy/$topic': typeof TematyTopicRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/huby': typeof HubyIndexRoute
  '/huby/$slug': typeof HubySlugRoute
  '/szukaj': typeof SzukajRoute
  '/archiwum': typeof ArchiwumIndexRoute
  '/archiwum/$year/$month': typeof ArchiwumYearMonthRoute
  '/o-serwisie': typeof OSerwisieRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/tematy/': typeof TematyIndexRoute
  '/tematy/$topic': typeof TematyTopicRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/huby/': typeof HubyIndexRoute
  '/huby/$slug': typeof HubySlugRoute
  '/szukaj': typeof SzukajRoute
  '/archiwum/': typeof ArchiwumIndexRoute
  '/archiwum/$year/$month': typeof ArchiwumYearMonthRoute
  '/o-serwisie': typeof OSerwisieRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/rss.xml'
    | '/tematy/'
    | '/tematy/$topic'
    | '/blog/$slug'
    | '/blog/'
    | '/huby/'
    | '/huby/$slug'
    | '/szukaj'
    | '/archiwum/'
    | '/archiwum/$year/$month'
    | '/o-serwisie'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/rss.xml'
    | '/tematy'
    | '/tematy/$topic'
    | '/blog/$slug'
    | '/blog'
    | '/huby'
    | '/huby/$slug'
    | '/szukaj'
    | '/archiwum'
    | '/archiwum/$year/$month'
    | '/o-serwisie'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/rss.xml'
    | '/tematy/'
    | '/tematy/$topic'
    | '/blog/$slug'
    | '/blog/'
    | '/huby/'
    | '/huby/$slug'
    | '/szukaj'
    | '/archiwum/'
    | '/archiwum/$year/$month'
    | '/o-serwisie'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  TematyIndexRoute: typeof TematyIndexRoute
  TematyTopicRoute: typeof TematyTopicRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  HubyIndexRoute: typeof HubyIndexRoute
  HubySlugRoute: typeof HubySlugRoute
  SzukajRoute: typeof SzukajRoute
  ArchiwumIndexRoute: typeof ArchiwumIndexRoute
  ArchiwumYearMonthRoute: typeof ArchiwumYearMonthRoute
  OSerwisieRoute: typeof OSerwisieRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tematy/': {
      id: '/tematy/'
      path: '/tematy'
      fullPath: '/tematy/'
      preLoaderRoute: typeof TematyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tematy/$topic': {
      id: '/tematy/$topic'
      path: '/tematy/$topic'
      fullPath: '/tematy/$topic'
      preLoaderRoute: typeof TematyTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huby/': {
      id: '/huby/'
      path: '/huby'
      fullPath: '/huby/'
      preLoaderRoute: typeof HubyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huby/$slug': {
      id: '/huby/$slug'
      path: '/huby/$slug'
      fullPath: '/huby/$slug'
      preLoaderRoute: typeof HubySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szukaj': {
      id: '/szukaj'
      path: '/szukaj'
      fullPath: '/szukaj'
      preLoaderRoute: typeof SzukajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archiwum/': {
      id: '/archiwum/'
      path: '/archiwum'
      fullPath: '/archiwum/'
      preLoaderRoute: typeof ArchiwumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archiwum/$year/$month': {
      id: '/archiwum/$year/$month'
      path: '/archiwum/$year/$month'
      fullPath: '/archiwum/$year/$month'
      preLoaderRoute: typeof ArchiwumYearMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-serwisie': {
      id: '/o-serwisie'
      path: '/o-serwisie'
      fullPath: '/o-serwisie'
      preLoaderRoute: typeof OSerwisieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  TematyIndexRoute: TematyIndexRoute,
  TematyTopicRoute: TematyTopicRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  HubyIndexRoute: HubyIndexRoute,
  HubySlugRoute: HubySlugRoute,
  SzukajRoute: SzukajRoute,
  ArchiwumIndexRoute: ArchiwumIndexRoute,
  ArchiwumYearMonthRoute: ArchiwumYearMonthRoute,
  OSerwisieRoute: OSerwisieRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
